added clustercleanade
The-Arcadis-Team/arc-station-14 pull request #88
Opened 2024-10-12 02:25 UTC by Creatorbot01

## About the PR
added a brand new shiny clustercleanade

## Why / Balance
to make cleaning up major and i mean major mess easier

## Media
![image](https://github.com/user-attachments/assets/e01f9252-f09d-4e3c-9981-852a68a4df72)

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: ClusterCleanade now available in janitorial crate
- remove: mopbucket from janitorial crate
- tweak: janibelt can now bring clustercleanade and util belt now can carry engi goggles in them

2024-10-12 02:27 UTC, Creatorbot01 commented
what why rsi validator just die??? wtf

2024-10-12 03:57 UTC, TheDoctor1977 commented
mop bucket removed from jani crate thank god
now you can actually close the damn thing after you open it

2024-10-12 18:01 UTC, Erisfiregamer1 commented
Please atempt to fix the grammar in the description before I explode.

2024-10-13 02:00 UTC, TheDoctor1977 requested changes

2024-10-13 02:00 UTC, TheDoctor1977 commented on Resources/Prototypes/Entities/Objects/Weapons/Throwable/clusterbang.yml
> +  description: Launches three cleanade. when it too messy for one cleanade how about 3 cleanade.(janitor.co does not responsible any mass slipping accident with this products)
```suggestion
  description: Launches three cleanades after the timer runs out.
```
this is parity with the clusterbang description

2024-10-13 02:00 UTC, TheDoctor1977 commented on Resources/Textures/Objects/Weapons/Grenades/clusterclean.rsi/meta.json
> +  "copyright": "Taken from tgstation and modified by Swept at https://github.com/tgstation/tgstation/commit/29c0ed1b000619cb5398ef921000a8d4502ba0b6 and modified by Swept",
the listed commit does not contain this sprite

2024-10-14 01:57 UTC, bruhmogus commented
cl should be
add: Clustercleanade now available in janitorial crates.
remove: Mop buckets will no longer spawn in janitorial crates, allowing them to be closed.
tweak: Janitor belts can carry clustercleanades, and utility belts can now hold engineering goggles.

2024-10-18 18:47 UTC, Erisfiregamer1 commented
PR is based on prebase code, redo your PR on the new code please.

2024-10-18 18:47 UTC, closed without merging